[build]
command = "yarn build"
publish = "build"

[build.environment]
NODE_VERSION = "14.17.3"
YARN_VERSION = "1.22.10"

[[headers]]
for = "/*"

[headers.values]
Basic-Auth = "4D:@30n1b1$"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
