export const errorMessages = {
  required: '入力してください',
  notOneOf: '正しい値を入力してください。',
  matches: '入力に誤りがあります。',
  notType: '正しいフォーマットで入力してください',
  length: '#{0}文字で入力してください',
  maxLength: '#{0}文字以内で入力してください',
  minLength: '#{0}文字以上で入力してください',
  maxNumber: '#{0}以下の数を入力してください',
  minNumber: '#{0}以上の数を入力してください',
  lessThanNumber: '#{0}未満の数を入力してください',
  moreThanNumber: '#{0}より大きい数を入力してください',
  minDate: '#{0}以降の日付を選択してください',
  maxDate: '#{0}以前の日付を選択してください',
  minArray: '#{0}以上をセットしてください',
  maxArray: '#{0}以下をセットしてください',
  email: '無効なメールアドレスです。',
  integer: '整数を入力してください',
} as const;
